#!/usr/bin/env python
#
# Copyright 2011 Oli McCormack. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# TODO (oli): reformat setup of these objects - this is a messy/inconsistent.

# for clientrax.txt
# all current metrics
cr_fields = [
("Header", ""), 
("AvgSpeed", "kn"), 
("Gusts", "kn"), 
("WindDir", "deg"), 
("OutTemp", "c"), 
("OutHum", "%"), 
("Baro", "hpa"), 
("RainDay", "mm"), 
("RainMon", "mm"), 
("RainYear", "mm"), 
("RainRate", "mm"), 
("MaxRainRate", "mm"), 
("InTemp", "c"), 
("InHum", "%"), 
("SoilTemp", "c"), 
("ForecastIcon", "Icon1"), 
("WMR968ExtraTemp", "c"), 
("WMR968ExtraHum", "%"), 
("WMR968ExtraSensor", "Number"), 
("YesterdayRain", "mm"), 
("ExtraTempSensor1", "c"), 
("ExtraTempSensor2", "c"), 
("ExtraTempSensor3", "c"), 
("ExtraTempSensor4", "c"), 
("ExtraTempSensor5", "c"), 
("ExtraTempSensor6", "c"), 
("ExtraHumSensor1", "%"), 
("ExtraHumSensor2", "%"), 
("ExtraHumSensor3", "%"), 
("Hour", "Time"), 
("Minute", "Time"), 
("Seconds", "Time"), 
("StationName", ""), 
("DallasLightningCount", "Number"), 
("SolarReading", "Number"), 
("Day", "Time"), 
("Month", "Time"), 
("WMR968Battery1", "%"), 
("WMR968Battery2", "%"), 
("WMR968Battery3", "%"), 
("WMR968Battery4", "%"), 
("WMR968Battery5", "%"), 
("WMR968Battery6", "%"), 
("WMR968Battery7", "%"), 
("WindChill", "c"), 
("Humidex", "c"), 
("MaxDayTemp", "c"), 
("MinDayTemp", "c"), 
("IconType", "Icon2"), 
("WeatherDesc", ""), 
("BaroTrend", "hpa"), 
("WindspeedHour1", "kn"), 
("WindspeedHour2", "kn"), 
("WindspeedHour3", "kn"), 
("WindspeedHour4", "kn"), 
("WindspeedHour5", "kn"), 
("WindspeedHour6", "kn"), 
("WindspeedHour7", "kn"), 
("WindspeedHour8", "kn"), 
("WindspeedHour9", "kn"), 
("WindspeedHour10", "kn"), 
("WindspeedHour11", "kn"), 
("WindspeedHour12", "kn"), 
("WindspeedHour13", "kn"), 
("WindspeedHour14", "kn"), 
("WindspeedHour15", "kn"), 
("WindspeedHour16", "kn"), 
("WindspeedHour17", "kn"), 
("WindspeedHour18", "kn"), 
("WindspeedHour19", "kn"), 
("WindspeedHour20", "kn"), 
("MaxWindGust", "kn"), 
("DewPointTemp", "c"), 
("CloudHeight", "ft"), 
("Date", ""), 
("MaxHumidex", "c"), 
("MinHumidex", "c"), 
("MaxWindchill", "c"), 
("MinWindchill", "c"), 
("UV", " "), 
("HrWindspeed1", "kn"), 
("HrWindspeed2", "kn"), 
("HrWindspeed3", "kn"), 
("HrWindspeed4", "kn"), 
("HrWindspeed5", "kn"), 
("HrWindspeed6", "kn"), 
("HrWindspeed7", "kn"), 
("HrWindspeed8", "kn"), 
("HrWindspeed9", "kn"), 
("HrWindspeed10", "kn"), 
("HrTemp1", "c"), 
("HrTemp2", "c"), 
("HrTemp3", "c"), 
("HrTemp4", "c"), 
("HrTemp5", "c"), 
("HrTemp6", "c"), 
("HrTemp7", "c"), 
("HrTemp8", "c"), 
("HrTemp9", "c"), 
("HrTemp10", "c"), 
("HrRain1", "mm"), 
("HrRain2", "mm"), 
("HrRain3", "mm"), 
("HrRain4", "mm"), 
("HrRain5", "mm"), 
("HrRain6", "mm"), 
("HrRain7", "mm"), 
("HrRain8", "mm"), 
("HrRain9", "mm"), 
("HrRain10", "mm"), 
("MaxHeatIndex", "c"), 
("MinHeatIndex", "c"), 
("HeatIndex", "c"), 
("MaxAvgSpeed", "kn"), 
("LightningLastMin", "Number"), 
("LightningLastTimeHour", "Time"), 
("LightningLastTimeMin", "Time"), 
("WindAvgDir", "deg"), 
("NexstormDist", ""), 
("NextStormBearing", "deg"), 
("ExtraTempSensor7", "c"), 
("ExtraTempSensor8", "c"), 
("ExtraHumSensor4", "%"), 
("ExtraHumSensor5", "%"), 
("ExtraHumSensor6", "%"), 
("ExtraHumSensor7", "%"), 
("ExtraHumSensor8", "%"), 
("SolarWM", "W/m&sup2, "), 
("MaxIndoorTemp", "c"), 
("MinIndoorTemp", "c"), 
("ApparentTemp", "c"), 
("MaxBaro", "hpa"), 
("MinBaro", "hpa"), 
("MaxGust", "kn"), 
("MaxGustLastHourTime", "Time"), 
("MaxGustTodayTime", "Time"), 
("MaxApparentTemp", "c"), 
("MinApparentTemp", "c"), 
("MaxDewpt", "c"), 
("MinDewpt", "c"), 
("MaxGustInLstMin", "kn"), 
("CurrentYear", "Time"), 
("THSWS", ""), 
("TempTrendLogic", "bool"), 
("HumidityTrendLogic", "bool"), 
("HumidexTrendLogic", "bool"), 
("HrWindDir1", "deg"), 
("HrWindDir2", "deg"), 
("HrWindDir3", "deg"), 
("HrWindDir4", "deg"), 
("HrWindDir5", "deg"), 
("HrWindDir6", "deg"), 
("HrWindDir7", "deg"), 
("HrWindDir8", "deg"), 
("HrWindDir9", "deg"), 
("HrWindDir10", "deg"), 
("LeafWetness", "c"), 
("Soilmoisture", "c"), 
("10MinAvgWindSpeed", "kn"), 
("Wetbulbtemperature", "c"), 
("LatitudeMinusEqualsSHemisphere)" ,   ""), 
("LongitudeMinusEASTofGMT"  ,   ""), 
("9amresetraintotal", "mm"), 
("Midnightresetraintotal", "mm"), 
("RecordEndWDVer", "")]


# a core group of selected, important current metrics
# format: (attribute identifier,
#          lookup for for clientraw.txt,
#          unit)
core = [
  ("wind_speed", "AvgSpeed", "kn"), 
  ("wind_gust", "Gusts", "kn"), 
  ("wind_direction",  "WindDir", "deg"), 
  ("out_temp", "OutTemp", "c"), 
  ("out_humidity", "OutHum", "%"), 
  ("pressure", "Baro", "hpa"), 
  ("rain_rate_daily", "RainDay", "mm"), 
  ("rain_rate_monthly", "RainMon", "mm"), 
  ("rain_rate_year", "RainYear", "mm"), 
  ("rain_rate", "RainRate", "mm"), 
  ("in_temp", "InTemp", "c"), 
  ("in_humidity", "InHum", "%"), 
  ("soil_temp", "SoilTemp", "c"),
  ("hour", "Hour", "Time"), 
  ("minute", "Minute", "Time"), 
  ("second", "Seconds", "Time"),  
  ("day", "Day", "Time"), 
  ("month", "Month", "Time")]

# for clientrawhour.txt
# format: (attribute type, start index, end index)
hourly_fields = [
("wind_speed",1,60),
("wind_gust",61,60),
("wind_dir",121,60),
("temp_out",181,60),
("humid_out",241,60),
("baro",301,60),
("rain",361,60),
("solar_wm",421,60)]

# for clientrawextra.txt
# format: (attribute type, start index, end index)
daily_fields = [
("wind_speed", (1,20), (562,4)),
("temp_out", (21,20), (566,4)),
("rain", (41,20), (570,4)),
("baro", (439,20), (574,4)),
("timestamps", (459,20), (578,4)),
("solar_wm", (491,20), (582,4)),
("solar_uv", (511,20), (586,4)),
("wind_dir", (536,20), (590,4)),
("humid_out", (611,20), (631,4)),
("temp_in", (636,20), (656,4))]

# for clientrawdaily.txt
# format: (attribute type, start index, end index)
monthly_fields = [
("temp_high",1,31),
("temp_low",32,31),
("rain",63,31),
("baro",94,31),
("wind_speed",125,31),
("wind_dir",156,31),
("humid_out",199,31),
("rain_year",187,12),
]

# mapping of value types => units
units = {
  "timestamps": 'Number',
  "wind_speed": "kn",
  "wind_gust": "kn",
  "wind_dir": "deg",
  "temp_out": "c",
  "temp_in": "c",
  "humid_out": "%",
  "baro": "hpa",
  "rain": "mm",
  "solar_wm": 'Number',
  "solar_uv": 'Number',
  "rain_year": 'mm',
  "temp_high": 'c',
  "temp_low": 'c',
}

